### PR TITLE
Add findWithRef

### PR DESCRIPTION
**Pull request by rkovacevic**
Lets you search by `ref`. What do you think?

### CODE REVIEW

**Comment by sheepsteak** [comment]
Thanks for contributing!

However, I'm a bit confused. The [React docs on shallow rendering](https://facebook.github.io/react/docs/test-utils.html#shallow-rendering) state that:

>Shallow testing currently has some limitations, namely not supporting refs. We're releasing this feature early and would appreciate the React community's feedback on how it should evolve.

It's possible the docs are just outdated as your PR clearly works!

**Comment by rkovacevic** [comment]
I'm curious about that myself. Submitted a question to react: facebook/react#5620

**Comment by rkovacevic** [comment]
Could you publish to npm? So I can use it directly in my project.

**Comment by sheepsteak** [comment]
Done. Thanks!

**Pull request merged**
